version: '3.5'

services:
  web:
    build: .
    image: golang-api
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: